INSERT INTO product_details (product_id, detail_key, detail_value) VALUES
(1, 'OS', 'Android 14'),
(1, 'Product Dimensions', '0.9 x 7.9 x 16.2 cm; 232 g'),
(1, 'Batteries', '1 12V batteries required. (included)'),
(1, 'Item model number', 'S928BZ'),
(1, 'Wireless communication technologies', 'Cellular'),
(1, 'Connectivity technologies', 'Bluetooth, NFC, USB, Wi-Fi'),
(1, 'GPS', 'True'),
(1, 'Special features', 'Always On Display, Built-In GPS, Dual SIM, Fast Charging Support, Mobile Hotspot Capability'),
(1, 'Other display features', 'Wireless'),
(1, 'Device interface - primary', 'Touchscreen with Stylus Support'),
(1, 'Resolution', '3120 x 1440'),
(1, 'Other camera features', 'Front, Rear'),
(1, 'Audio Jack', 'USB Type C'),
(1, 'Form factor', 'Bar'),
(1, 'Colour', 'Titanium Gray'),
(1, 'Battery Power Rating', '5000 Milliamp Hours'),
(1, 'Whats in the box', 'Data Cable (Type C-to-C), Quick Start Guide, SIM Tray Ejector, Smartphone, Stylus'),
(1, 'Manufacturer', 'Samsung'),
(1, 'Country of Origin', 'India'),
(1, 'Item Weight', '232 g'),
(1, 'ASIN', 'B0CS5XW6TN');